-- Orlando theme park attractions (catalogue). Park IDs: mk, ep, hs, ak, us, ioa, eu
-- Idempotent upserts (avoid delete — would cascade to trip_ride_priorities).

insert into attractions (
  id, park_id, name, category, height_requirement_cm, thrill_level, is_indoor, duration_minutes,
  skip_line_system, skip_line_tier, skip_line_notes, avg_wait_peak_minutes, avg_wait_offpeak_minutes,
  best_time_to_ride, sort_order, is_seasonal, is_temporarily_closed, closure_note, tags, official_url
) values
-- Magic Kingdom
('mk-tron-lightcycle', 'mk', 'TRON Lightcycle / Run', 'ride', 122, 'intense', false, 2,
 'disney_lightning_lane', 'single_pass', null, 90, 45, 'Rope drop or last hour', 10, false, false, null,
 array['roller_coaster','thrilling']::text[], null),
('mk-seven-dwarfs', 'mk', 'Seven Dwarfs Mine Train', 'ride', 97, 'moderate', false, 3,
 'disney_lightning_lane', 'single_pass', null, 80, 40, 'Evening or rope drop', 20, false, false, null,
 array['roller_coaster','family','dark_ride']::text[], null),
('mk-tianas-bayou', 'mk', 'Tiana''s Bayou Adventure', 'ride', 102, 'moderate', true, 8,
 'disney_lightning_lane', 'multi_pass_tier1', null, 70, 35, 'LL Multi Pass recommended', 30, false, false, null,
 array['dark_ride','family','water_ride']::text[], null),
('mk-big-thunder', 'mk', 'Big Thunder Mountain Railroad', 'ride', 97, 'thrilling', false, 4,
 'disney_lightning_lane', 'multi_pass_tier1', null, 60, 25, 'Rope drop or evening', 40, false, false, null,
 array['roller_coaster','family']::text[], null),
('mk-jungle-cruise', 'mk', 'Jungle Cruise', 'ride', null, 'gentle', false, 10,
 'disney_lightning_lane', 'multi_pass_tier1', null, 55, 20, 'Evening or LL', 50, false, false, null,
 array['family','boat_ride']::text[], null),
('mk-peter-pan', 'mk', 'Peter Pan''s Flight', 'ride', null, 'gentle', true, 3,
 'disney_lightning_lane', 'multi_pass_tier1', null, 65, 30, 'LL Multi Pass — always long waits', 60, false, false, null,
 array['dark_ride','family','classic']::text[], null),
('mk-space-mountain', 'mk', 'Space Mountain', 'ride', 112, 'thrilling', true, 3,
 'disney_lightning_lane', 'multi_pass_tier1', null, 50, 20, 'First hour or last hour', 70, false, false, null,
 array['roller_coaster','dark_ride','classic']::text[], null),
('mk-pirates', 'mk', 'Pirates of the Caribbean', 'ride', null, 'gentle', true, 12,
 'disney_lightning_lane', 'multi_pass_tier2', null, 30, 10, 'Rarely needs LL — high capacity', 80, false, false, null,
 array['dark_ride','family','classic','boat_ride']::text[], null),
('mk-haunted-mansion', 'mk', 'Haunted Mansion', 'ride', null, 'gentle', true, 10,
 'disney_lightning_lane', 'multi_pass_tier2', null, 35, 15, 'Good LL burner — early morning slot', 90, false, false, null,
 array['dark_ride','family','classic']::text[], null),
('mk-buzz-lightyear', 'mk', 'Buzz Lightyear''s Space Ranger Spin', 'ride', null, 'gentle', true, 5,
 'disney_lightning_lane', 'multi_pass_tier2', null, 40, 15, 'Afternoon', 100, false, false, null,
 array['dark_ride','family','interactive']::text[], null),
('mk-splash-mountain', 'mk', 'it''s a small world', 'ride', null, 'gentle', true, 12,
 'disney_lightning_lane', 'multi_pass_tier2', null, 20, 10, 'Rarely needs LL', 110, false, false, null,
 array['dark_ride','family','classic','boat_ride']::text[], null),
('mk-dumbo', 'mk', 'Dumbo the Flying Elephant', 'ride', null, 'gentle', false, 2,
 'disney_lightning_lane', 'multi_pass_tier2', null, 25, 10, 'Morning or evening', 120, false, false, null,
 array['family','spinner']::text[], null),
('mk-barnstormer', 'mk', 'The Barnstormer', 'ride', 89, 'moderate', false, 1,
 'disney_lightning_lane', 'multi_pass_tier2', null, 20, 10, 'Morning', 130, false, false, null,
 array['roller_coaster','family']::text[], null),

-- EPCOT
('ep-guardians-galaxy', 'ep', 'Guardians of the Galaxy: Cosmic Rewind', 'ride', 107, 'intense', true, 3,
 'disney_lightning_lane', 'single_pass', null, 85, 40, 'Virtual queue or rope drop', 10, false, false, null,
 array['roller_coaster','thrilling','dark_ride']::text[], null),
('ep-frozen-ever-after', 'ep', 'Frozen Ever After', 'ride', null, 'gentle', true, 5,
 'disney_lightning_lane', 'multi_pass_tier1', null, 60, 25, 'LL or rope drop', 20, false, false, null,
 array['dark_ride','family','boat_ride']::text[], null),
('ep-remys-ratatouille', 'ep', 'Remy''s Ratatouille Adventure', 'ride', null, 'gentle', true, 5,
 'disney_lightning_lane', 'multi_pass_tier1', null, 55, 20, 'LL — books fast', 30, false, false, null,
 array['dark_ride','family','trackless']::text[], null),
('ep-test-track', 'ep', 'Test Track', 'ride', 102, 'thrilling', false, 5,
 'disney_lightning_lane', 'multi_pass_tier1', null, 65, 30, 'Rope drop or single rider', 40, false, false, null,
 array['thrilling','interactive']::text[], null),
('ep-soarin', 'ep', 'Soarin'' Around the World', 'ride', 102, 'moderate', true, 5,
 'disney_lightning_lane', 'multi_pass_tier2', null, 45, 20, 'Tier 2 LL or rope drop', 50, false, false, null,
 array['family','simulator']::text[], null),
('ep-mission-space', 'ep', 'Mission: SPACE', 'ride', 112, 'intense', true, 5,
 'disney_lightning_lane', 'multi_pass_tier2', null, 30, 10, 'Afternoon — Green side for families', 60, false, false, null,
 array['simulator','thrilling']::text[], null),
('ep-spaceship-earth', 'ep', 'Spaceship Earth', 'ride', null, 'gentle', true, 15,
 'disney_lightning_lane', 'multi_pass_tier2', null, 25, 10, 'Afternoon', 70, false, false, null,
 array['dark_ride','family','classic']::text[], null),
('ep-living-with-land', 'ep', 'Living with the Land', 'ride', null, 'gentle', true, 14,
 'disney_lightning_lane', 'multi_pass_tier2', null, 20, 10, 'Afternoon', 80, false, false, null,
 array['family','boat_ride','educational']::text[], null),
('ep-nemo-seas', 'ep', 'The Seas with Nemo & Friends', 'ride', null, 'gentle', true, 5,
 'disney_lightning_lane', 'multi_pass_tier2', null, 15, 5, 'Rarely needs LL', 90, false, false, null,
 array['dark_ride','family']::text[], null),
('ep-figment', 'ep', 'Journey Into Imagination with Figment', 'ride', null, 'gentle', true, 8,
 'disney_lightning_lane', 'multi_pass_tier2', null, 15, 5, 'Rarely needs LL', 100, false, false, null,
 array['dark_ride','family','classic']::text[], null),

-- Hollywood Studios
('hs-rise-resistance', 'hs', 'Star Wars: Rise of the Resistance', 'ride', 102, 'thrilling', true, 18,
 'disney_lightning_lane', 'single_pass', null, 90, 50, 'LL Single Pass or rope drop', 10, false, false, null,
 array['dark_ride','thrilling','trackless']::text[], null),
('hs-slinky-dog', 'hs', 'Slinky Dog Dash', 'ride', 97, 'moderate', false, 2,
 'disney_lightning_lane', 'multi_pass_tier1', null, 70, 30, 'Rope drop or LL', 20, false, false, null,
 array['roller_coaster','family']::text[], null),
('hs-mickey-runaway', 'hs', 'Mickey & Minnie''s Runaway Railway', 'ride', null, 'gentle', true, 5,
 'disney_lightning_lane', 'multi_pass_tier1', null, 50, 20, 'Afternoon LL', 30, false, false, null,
 array['dark_ride','family','trackless']::text[], null),
('hs-tower-terror', 'hs', 'The Twilight Zone Tower of Terror', 'ride', 102, 'intense', true, 2,
 'disney_lightning_lane', 'multi_pass_tier1', null, 55, 25, 'Evening or LL', 40, false, false, null,
 array['thrilling','drop_ride','classic']::text[], null),
('hs-toy-story-mania', 'hs', 'Toy Story Mania!', 'ride', null, 'gentle', true, 7,
 'disney_lightning_lane', 'multi_pass_tier2', null, 40, 15, 'Afternoon', 50, false, false, null,
 array['family','interactive','dark_ride']::text[], null),
('hs-smugglers-run', 'hs', 'Millennium Falcon: Smugglers Run', 'ride', 97, 'moderate', true, 5,
 'disney_lightning_lane', 'multi_pass_tier2', null, 35, 15, 'Afternoon or single rider', 60, false, false, null,
 array['simulator','thrilling']::text[], null),
('hs-rock-n-roller', 'hs', 'Rock ''n'' Roller Coaster', 'ride', 122, 'intense', true, 1,
 'disney_lightning_lane', 'multi_pass_tier1',
 'May be closed for refurbishment for portions of 2026 — check park times before you go.',
 60, 25, 'Evening or LL when operating', 70, false, false, null,
 array['roller_coaster','thrilling','dark_ride']::text[], null),
('hs-alien-saucers', 'hs', 'Alien Swirling Saucers', 'ride', 81, 'gentle', true, 2,
 'disney_lightning_lane', 'multi_pass_tier2', null, 25, 10, 'Rarely needs LL', 80, false, false, null,
 array['family','spinner']::text[], null),

-- Animal Kingdom
('ak-flight-of-passage', 'ak', 'Avatar Flight of Passage', 'ride', 112, 'intense', true, 5,
 'disney_lightning_lane', 'single_pass', null, 85, 40, 'LL Single Pass or rope drop', 10, false, false, null,
 array['simulator','thrilling']::text[], null),
('ak-expedition-everest', 'ak', 'Expedition Everest', 'ride', 112, 'thrilling', false, 3,
 'disney_lightning_lane', 'multi_pass_tier2', null, 45, 15, 'Morning or evening', 20, false, false, null,
 array['roller_coaster','thrilling']::text[], null),
('ak-kilimanjaro-safaris', 'ak', 'Kilimanjaro Safaris', 'ride', null, 'gentle', false, 22,
 'disney_lightning_lane', 'multi_pass_tier2', null, 50, 20, 'Early morning for best animal viewing', 30, false, false, null,
 array['family','outdoor','safari']::text[], null),
('ak-navi-river', 'ak', 'Na''vi River Journey', 'ride', null, 'gentle', true, 5,
 'disney_lightning_lane', 'multi_pass_tier2', null, 55, 20, 'Afternoon', 40, false, false, null,
 array['dark_ride','family','boat_ride']::text[], null),
('ak-kali-river', 'ak', 'Kali River Rapids', 'ride', 97, 'moderate', false, 5,
 'disney_lightning_lane', 'multi_pass_tier2', null, 30, 10, 'Afternoon on hot days', 50, false, false, null,
 array['water_ride','family']::text[], null),
('ak-dinosaur', 'ak', 'DINOSAUR', 'ride', 102, 'thrilling', true, 4,
 'disney_lightning_lane', 'multi_pass_tier2', null, 30, 10, 'Permanently closing February 2026', 60, false, true,
 'Closed permanently from February 2026 — remove from touring plans.',
 array['dark_ride','thrilling']::text[], null),

-- Universal Studios Florida
('usf-hagrids-motorbike', 'us', 'Hagrid''s Magical Creatures Motorbike Adventure', 'ride', 122, 'thrilling', false, 3,
 'universal_express', 'express',
 'Historically no Express on this ride — rope drop is the most reliable strategy.', 90, 40, 'Rope drop', 10, false, false, null,
 array['roller_coaster','thrilling','outdoor']::text[], null),
('usf-revenge-mummy', 'us', 'Revenge of the Mummy', 'ride', 122, 'thrilling', true, 3,
 'universal_express', 'express', null, 50, 20, 'Afternoon or Express', 20, false, false, null,
 array['roller_coaster','dark_ride','thrilling']::text[], null),
('usf-transformers', 'us', 'Transformers: The Ride 3D', 'ride', 102, 'moderate', true, 5,
 'universal_express', 'express', null, 40, 15, 'Express or afternoon', 30, false, false, null,
 array['simulator','dark_ride']::text[], null),
('usf-minion-mayhem', 'us', 'Despicable Me Minion Mayhem', 'ride', 102, 'gentle', true, 5,
 'universal_express', 'express', null, 45, 20, 'Express strongly recommended — low capacity', 40, false, false, null,
 array['simulator','family']::text[], null),
('usf-gringotts', 'us', 'Harry Potter and the Escape from Gringotts', 'ride', 107, 'thrilling', true, 5,
 'universal_express', 'express', null, 60, 25, 'Rope drop or Express', 50, false, false, null,
 array['dark_ride','thrilling','roller_coaster']::text[], null),
('usf-et-adventure', 'us', 'E.T. Adventure', 'ride', 86, 'gentle', true, 5,
 'universal_express', 'express', null, 25, 10, 'Afternoon', 60, false, false, null,
 array['dark_ride','family','classic']::text[], null),
('usf-men-in-black', 'us', 'Men in Black Alien Attack', 'ride', 107, 'moderate', true, 5,
 'universal_express', 'express', null, 30, 10, 'Afternoon or Express', 70, false, false, null,
 array['dark_ride','interactive']::text[], null),
('usf-rip-ride-rockit', 'us', 'Hollywood Rip Ride Rockit', 'ride', 130, 'intense', false, 2,
 'universal_express', 'express',
 'May be closed for replacement in 2026 — check Universal''s official park calendar.',
 50, 20, 'When operating: midday often shorter than morning', 80, false, false, null,
 array['roller_coaster','thrilling']::text[], null),

-- Islands of Adventure (VelociCoaster only — second table row was duplicate listing)
('ioa-velocicoaster', 'ioa', 'Jurassic World VelociCoaster', 'ride', 130, 'intense', false, 3,
 'universal_express', 'express', null, 70, 30, 'Rope drop or Express', 10, false, false, null,
 array['roller_coaster','thrilling']::text[], null),
('ioa-forbidden-journey', 'ioa', 'Harry Potter and the Forbidden Journey', 'ride', 122, 'thrilling', true, 5,
 'universal_express', 'express', null, 55, 20, 'Express or morning', 20, false, false, null,
 array['dark_ride','simulator','thrilling']::text[], null),
('ioa-hulk', 'ioa', 'The Incredible Hulk Coaster', 'ride', 137, 'intense', false, 2,
 'universal_express', 'express', null, 45, 15, 'Morning', 30, false, false, null,
 array['roller_coaster','thrilling']::text[], null),
('ioa-hagrid-falls', 'ioa', 'Dudley Do-Right''s Ripsaw Falls', 'ride', 112, 'thrilling', false, 5,
 'universal_express', 'express', null, 35, 15, 'Hot afternoons', 40, false, false, null,
 array['water_ride','family']::text[], null),
('ioa-spiderman', 'ioa', 'The Amazing Adventures of Spider-Man', 'ride', 102, 'moderate', true, 5,
 'universal_express', 'express', null, 30, 10, 'Afternoon', 50, false, false, null,
 array['dark_ride','simulator']::text[], null),
('ioa-flight-hippogriff', 'ioa', 'Flight of the Hippogriff', 'ride', 91, 'gentle', false, 1,
 'universal_express', 'express', null, 30, 10, 'Morning with Hogsmeade', 60, false, false, null,
 array['roller_coaster','family']::text[], null),
('ioa-popeyes-barges', 'ioa', 'Popeye & Bluto''s Bilge-Rat Barges', 'ride', 107, 'moderate', false, 5,
 'universal_express', 'express', null, 25, 10, 'Hot afternoons', 70, false, false, null,
 array['water_ride','family']::text[], null),

-- Epic Universe
('eu-stardust-racers', 'eu', 'Stardust Racers', 'ride', 122, 'thrilling', false, 3,
 'universal_express', 'express', null, 80, 35, 'Rope drop', 10, false, false, null,
 array['roller_coaster','thrilling','dueling']::text[], null),
('eu-battle-ministry', 'eu', 'Harry Potter and the Battle at the Ministry', 'ride', 122, 'thrilling', true, 5,
 'universal_express', 'express', null, 90, 45, 'Rope drop — highest demand ride', 20, false, false, null,
 array['dark_ride','thrilling']::text[], null),
('eu-yoshi-adventure', 'eu', 'Yoshi''s Adventure', 'ride', null, 'gentle', false, 5,
 'universal_express', 'express', null, 40, 15, 'Morning or Express', 30, false, false, null,
 array['family','outdoor','trackless']::text[], null),
('eu-mario-kart', 'eu', 'Mario Kart: Bowser''s Challenge', 'ride', 107, 'moderate', true, 5,
 'universal_express', 'express', null, 70, 30, 'Express or rope drop', 40, false, false, null,
 array['dark_ride','interactive','simulator']::text[], null),
('eu-donkey-kong', 'eu', 'Mine-Cart Madness', 'ride', 107, 'thrilling', false, 3,
 'universal_express', 'express', null, 65, 25, 'Morning', 50, false, false, null,
 array['roller_coaster','family']::text[], null),
('eu-how-to-train', 'eu', 'How to Train Your Dragon: Hiccup''s Wing Gliders', 'ride', 102, 'moderate', false, 3,
 'universal_express', 'express', null, 50, 20, 'Afternoon', 60, false, false, null,
 array['family','outdoor','suspended']::text[], null),
('eu-curse-werewolf', 'eu', 'Curse of the Werewolf', 'ride', 122, 'intense', true, 3,
 'universal_express', 'express', null, 60, 25, 'Evening', 70, false, false, null,
 array['dark_ride','thrilling']::text[], null),
('eu-monsters-unchained', 'eu', 'Monsters Unchained', 'ride', 107, 'thrilling', true, 5,
 'universal_express', 'express', null, 55, 20, 'Afternoon or Express', 80, false, false, null,
 array['dark_ride','thrilling','trackless']::text[], null)
on conflict (id) do update set
  park_id = excluded.park_id,
  name = excluded.name,
  category = excluded.category,
  height_requirement_cm = excluded.height_requirement_cm,
  thrill_level = excluded.thrill_level,
  is_indoor = excluded.is_indoor,
  duration_minutes = excluded.duration_minutes,
  skip_line_system = excluded.skip_line_system,
  skip_line_tier = excluded.skip_line_tier,
  skip_line_notes = excluded.skip_line_notes,
  avg_wait_peak_minutes = excluded.avg_wait_peak_minutes,
  avg_wait_offpeak_minutes = excluded.avg_wait_offpeak_minutes,
  best_time_to_ride = excluded.best_time_to_ride,
  sort_order = excluded.sort_order,
  is_seasonal = excluded.is_seasonal,
  is_temporarily_closed = excluded.is_temporarily_closed,
  closure_note = excluded.closure_note,
  tags = excluded.tags,
  official_url = excluded.official_url,
  updated_at = now();
