-- Assignable named restaurant tiles (sort_order >= 900) + optional table booking URL.
-- Destinations left null where the column allows; region_ids drive planner filtering.

alter table public.parks
  add column if not exists affiliate_ticket_url text;

-- UK-wide region list for shared chain rows (Prezzo, Harvester, Toby, Wagamama, Pizza Express, Nando's).
-- VERIFY: confirm region id spellings match `regions.id` in your Supabase project.
insert into public.parks (
  name,
  icon,
  bg_colour,
  fg_colour,
  park_group,
  destinations,
  region_ids,
  is_custom,
  sort_order,
  affiliate_ticket_url
)
values
  ('LongHorn Steakhouse', '🥩', '#8B4513', '#FFFFFF', 'dining', null, array['orlando','florida_combo','miami']::text[], false, 900, null),
  ('The Cheesecake Factory', '🍽️', '#8B6914', '#FFFFFF', 'dining', null, array['orlando','florida_combo','cali','miami','lasvegas','uae']::text[], false, 901, null),
  ('Olive Garden', '🍕', '#CC5500', '#FFFFFF', 'dining', null, array['orlando','florida_combo','cali']::text[], false, 902, null),
  ('Chick-fil-A', '🍗', '#DAA520', '#FFFFFF', 'dining', null, array['orlando','florida_combo','cali','lasvegas']::text[], false, 903, null),
  ('Texas Roadhouse', '🥩', '#8B4513', '#FFFFFF', 'dining', null, array['orlando','florida_combo','uae']::text[], false, 904, null),
  ('Buca di Beppo', '🍕', '#CC5500', '#FFFFFF', 'dining', null, array['orlando','florida_combo']::text[], false, 905, null),
  ('Bahama Breeze', '🍽️', '#2E8B8B', '#FFFFFF', 'dining', null, array['orlando','florida_combo']::text[], false, 906, null),
  ('Bubba Gump Shrimp Co.', '🦐', '#2E8B8B', '#FFFFFF', 'dining', null, array['orlando','florida_combo']::text[], false, 907, null),
  ('Outback Steakhouse', '🥩', '#8B4513', '#FFFFFF', 'dining', null, array['orlando','florida_combo']::text[], false, 908, null),
  ('Raising Cane''s', '🍗', '#DAA520', '#FFFFFF', 'dining', null, array['orlando','florida_combo','lasvegas']::text[], false, 909, null),
  ('Flanigan''s Seafood', '🦐', '#2E8B8B', '#FFFFFF', 'dining', null, array['miami','florida_combo']::text[], false, 910, null),
  ('Pollo Tropical', '🍗', '#DAA520', '#FFFFFF', 'dining', null, array['miami','florida_combo']::text[], false, 911, null),
  ('Publix Deli', '🥪', '#D2946B', '#FFFFFF', 'dining', null, array['miami','florida_combo']::text[], false, 912, null),
  ('Shake Shack', '🍔', '#B8860B', '#FFFFFF', 'dining', null, array['miami','florida_combo']::text[], false, 913, null),
  ('In-N-Out Burger', '🍔', '#B8860B', '#FFFFFF', 'dining', null, array['cali','lasvegas']::text[], false, 914, null),
  ('BJ''s Restaurant & Brewhouse', '🍕', '#CC5500', '#FFFFFF', 'dining', null, array['cali']::text[], false, 915, null),
  ('Rubio''s Coastal Grill', '🌮', '#2E8B8B', '#FFFFFF', 'dining', null, array['cali']::text[], false, 916, null),
  ('Red Robin', '🍔', '#B8860B', '#FFFFFF', 'dining', null, array['cali']::text[], false, 917, null),
  ('El Pollo Loco', '🍗', '#DAA520', '#FFFFFF', 'dining', null, array['cali']::text[], false, 918, null),
  ('Heart Attack Grill', '🍔', '#B8860B', '#FFFFFF', 'dining', null, array['lasvegas']::text[], false, 919, null),
  ('Hash House A Go Go', '🍽️', '#8B6914', '#FFFFFF', 'dining', null, array['lasvegas']::text[], false, 920, null),
  ('Hippopotamus', '🥩', '#8B4513', '#FFFFFF', 'dining', null, array['paris']::text[], false, 921, null),
  ('Flunch', '🍽️', '#8B6914', '#FFFFFF', 'dining', null, array['paris']::text[], false, 922, null),
  ('Léon de Bruxelles', '🦐', '#2E8B8B', '#FFFFFF', 'dining', null, array['paris']::text[], false, 923, null),
  ('Buffalo Grill', '🍔', '#B8860B', '#FFFFFF', 'dining', null, array['paris']::text[], false, 924, null),
  ('Paul', '🥐', '#D2946B', '#FFFFFF', 'dining', null, array['paris']::text[], false, 925, null),
  ('Brioche Dorée', '🥐', '#D2946B', '#FFFFFF', 'dining', null, array['paris']::text[], false, 926, null),
  ('Wagamama', '🍜', '#CD5C5C', '#FFFFFF', 'dining', null, array['london','edinburgh','bath','liverpool','york','manchester','cambridge','lakedist','cornwall','highlands','cardiff','belfast','brighton','stratfm','uk_combo','uk']::text[], false, 927, null),
  ('Nando''s', '🍗', '#DAA520', '#FFFFFF', 'dining', null, array['london','edinburgh','bath','liverpool','york','manchester','cambridge','lakedist','cornwall','highlands','cardiff','belfast','brighton','stratfm','uk_combo','uk','goldcoast','uae']::text[], false, 928, null),
  ('Pizza Express', '🍕', '#CC5500', '#FFFFFF', 'dining', null, array['london','edinburgh','bath','liverpool','york','manchester','cambridge','lakedist','cornwall','highlands','cardiff','belfast','brighton','stratfm','uk_combo','uk']::text[], false, 929, null),
  ('GBK (Gourmet Burger Kitchen)', '🍔', '#B8860B', '#FFFFFF', 'dining', null, array['london','uk_combo']::text[], false, 930, null),
  ('Dishoom', '🍛', '#CD5C5C', '#FFFFFF', 'dining', null, array['london','uk_combo']::text[], false, 931, null),
  ('The Ivy', '🍽️', '#8B6914', '#FFFFFF', 'dining', null, array['london','uk_combo']::text[], false, 932, null),
  ('Leon', '🥗', '#6B8E23', '#FFFFFF', 'dining', null, array['london','uk_combo']::text[], false, 933, null),
  ('Honest Burgers', '🍔', '#B8860B', '#FFFFFF', 'dining', null, array['london','uk_combo']::text[], false, 934, null),
  ('Mums Great Comfort Food', '🍽️', '#8B6914', '#FFFFFF', 'dining', null, array['edinburgh','uk_combo']::text[], false, 935, null),
  ('CoCo Ichibanya', '🍛', '#CD5C5C', '#FFFFFF', 'dining', null, array['tokyo']::text[], false, 936, null),
  ('Ichiran Ramen', '🍜', '#CD5C5C', '#FFFFFF', 'dining', null, array['tokyo']::text[], false, 937, null),
  ('Genki Sushi', '🍣', '#2E8B8B', '#FFFFFF', 'dining', null, array['tokyo']::text[], false, 938, null),
  ('Saizeriya', '🍕', '#CC5500', '#FFFFFF', 'dining', null, array['tokyo']::text[], false, 939, null),
  ('Mos Burger', '🍔', '#B8860B', '#FFFFFF', 'dining', null, array['tokyo']::text[], false, 940, null),
  ('Yoshinoya', '🍜', '#CD5C5C', '#FFFFFF', 'dining', null, array['tokyo']::text[], false, 941, null),
  ('Shakespeare and Co.', '☕', '#D2946B', '#FFFFFF', 'dining', null, array['uae']::text[], false, 942, null),
  ('Al Fanar', '🍽️', '#8B6914', '#FFFFFF', 'dining', null, array['uae']::text[], false, 943, null),
  ('Pancakes in Paradise', '🥞', '#D2946B', '#FFFFFF', 'dining', null, array['goldcoast']::text[], false, 944, null),
  ('Grill''d', '🍔', '#B8860B', '#FFFFFF', 'dining', null, array['goldcoast']::text[], false, 945, null),
  ('Betty''s Burgers', '🍔', '#B8860B', '#FFFFFF', 'dining', null, array['goldcoast']::text[], false, 946, null),
  ('Ya Kun Kaya Toast', '☕', '#D2946B', '#FFFFFF', 'dining', null, array['singapore']::text[], false, 947, null),
  ('Din Tai Fung', '🥟', '#CD5C5C', '#FFFFFF', 'dining', null, array['singapore']::text[], false, 948, null),
  ('Toast Box', '☕', '#D2946B', '#FFFFFF', 'dining', null, array['singapore']::text[], false, 949, null),
  ('Jumbo Seafood', '🦀', '#2E8B8B', '#FFFFFF', 'dining', null, array['singapore']::text[], false, 950, null),
  ('Myeongdong Kyoja', '🍜', '#CD5C5C', '#FFFFFF', 'dining', null, array['seoul']::text[], false, 951, null),
  ('Tosokchon Samgyetang', '🍲', '#CD5C5C', '#FFFFFF', 'dining', null, array['seoul']::text[], false, 952, null),
  ('Isaac Toast', '🥪', '#D2946B', '#FFFFFF', 'dining', null, array['seoul']::text[], false, 953, null),
  ('BHC Chicken', '🍗', '#DAA520', '#FFFFFF', 'dining', null, array['seoul']::text[], false, 954, null),
  ('Prezzo', '🍕', '#CC5500', '#FFFFFF', 'dining', null, array['london','edinburgh','bath','liverpool','york','manchester','cambridge','lakedist','cornwall','highlands','cardiff','belfast','brighton','stratfm','uk_combo','uk']::text[], false, 955, null),
  ('Harvester', '🍽️', '#8B6914', '#FFFFFF', 'dining', null, array['london','edinburgh','bath','liverpool','york','manchester','cambridge','lakedist','cornwall','highlands','cardiff','belfast','brighton','stratfm','uk_combo','uk']::text[], false, 956, null),
  ('Toby Carvery', '🍖', '#8B4513', '#FFFFFF', 'dining', null, array['london','edinburgh','bath','liverpool','york','manchester','cambridge','lakedist','cornwall','highlands','cardiff','belfast','brighton','stratfm','uk_combo','uk']::text[], false, 957, null);
