#!/usr/bin/env tsx
/**
 * Generates supabase/seeds/live_wait_park_mappings.sql from Queue-Times parks.json
 * plus name matching against TripTiles `parks` rows (scraped from migration SQL).
 *
 * Run: npx tsx scripts/generate-live-wait-park-mappings-seed.ts
 */

import { readdirSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";

const PROVIDER = "queue_times";

type QtPark = { id: number; name: string; group: string };
type TtPark = { id: string; name: string };

/** QT park id → TripTiles parks.id (null = leave unmapped). */
const MANUAL_QT_TO_TT: Record<number, string | null> = {
  335: null, // Six Flags Qiddiya — skip entirely (no TripTiles park)
  54: "plops",
  302: "plopsde",
  28: "wdsp",
  6: "mk",
  5: "ep",
  7: "hs",
  8: "ak",
  65: "us",
  64: "ioa",
  334: "eu",
  67: "vb",
  21: "sw",
  24: "bg",
  16: "dl",
  17: "dca",
  66: "ush",
  61: "knot",
  4: "dlp",
  31: "hkdl",
  1: "alton",
  2: "thorpe",
  3: "chess",
  27: "legoukw",
  25: "heide",
  52: "legobill",
  278: "legodeu",
  279: "llc",
  280: "ll",
  12: "garda",
  9: "ast",
  291: "fut",
  14: "walbel",
  53: "walib",
  51: "europa",
  160: "eft",
  274: "tdl",
  275: "tds",
  284: "usj",
  58: "cwond",
  273: "bppb",
  290: "djurs",
};

function escapeSqlString(s: string): string {
  return s.replace(/'/g, "''");
}

function normalise(s: string): string {
  return s
    .toLowerCase()
    .replace(/['’]/g, "")
    .replace(/[^a-z0-9]+/g, " ")
    .replace(/\s+/g, " ")
    .trim();
}

function loadTripTilesParks(): TtPark[] {
  const dir = join(process.cwd(), "supabase", "migrations");
  const files = readdirSync(dir).filter(
    (f) => f.includes("parks") && f.endsWith(".sql"),
  );
  const byId = new Map<string, string>();
  const re = /^\('([a-z0-9_-]+)',\s*'((?:''|[^'])*)'/gm;
  for (const f of files) {
    const text = readFileSync(join(dir, f), "utf8");
    let m: RegExpExecArray | null;
    while ((m = re.exec(text)) !== null) {
      const id = m[1]!;
      const name = m[2]!.replace(/''/g, "'");
      byId.set(id, name);
    }
  }
  return [...byId.entries()].map(([id, name]) => ({ id, name }));
}

async function loadQtParks(): Promise<QtPark[]> {
  const res = await fetch("https://queue-times.com/parks.json");
  if (!res.ok) throw new Error(`parks.json ${res.status}`);
  const j = (await res.json()) as { id: number; name: string; parks: QtPark[] }[];
  const flat: QtPark[] = [];
  for (const g of j) {
    for (const p of g.parks ?? []) {
      flat.push({ id: p.id, name: p.name, group: g.name });
    }
  }
  return flat;
}

async function main() {
  const tt = loadTripTilesParks();
  const ttByNorm = new Map<string, TtPark[]>();
  for (const p of tt) {
    const k = normalise(p.name);
    const list = ttByNorm.get(k) ?? [];
    list.push(p);
    ttByNorm.set(k, list);
  }

  const qt = await loadQtParks();
  const filtered = qt.filter((p) => p.id !== 335).sort((a, b) => a.id - b.id);

  const rows: { qt: QtPark; parkId: string | null }[] = [];
  for (const q of filtered) {
    let parkId: string | null = null;
    if (Object.prototype.hasOwnProperty.call(MANUAL_QT_TO_TT, q.id)) {
      parkId = MANUAL_QT_TO_TT[q.id] ?? null;
    } else {
      const exact = ttByNorm.get(normalise(q.name));
      if (exact?.length === 1) parkId = exact[0]!.id;
      else {
        const nq = normalise(q.name);
        const loose = tt.find((t) => normalise(t.name) === nq);
        parkId = loose?.id ?? null;
      }
    }
    rows.push({ qt: q, parkId });
  }

  const lines: string[] = [
    "-- Generated by scripts/generate-live-wait-park-mappings-seed.ts",
    "-- Queue-Times flat parks excluding QT id 335 (Six Flags Qiddiya City — no TripTiles park).",
    "-- Upsert key: (provider, external_park_id) — matches unique constraint on live_wait_park_mappings",
    "-- (one row per Queue-Times park; park_id nullable when TripTiles has no catalogue row yet).",
    "",
    "insert into public.live_wait_park_mappings (park_id, provider, external_park_id, external_park_name)",
    "values",
  ];

  const valueLines = rows.map(({ qt: q, parkId }) => {
    const pid = parkId === null ? "null" : `'${escapeSqlString(parkId)}'`;
    return `  (${pid}, '${PROVIDER}', '${q.id}', '${escapeSqlString(q.name)}')`;
  });
  lines.push(valueLines.join(",\n"));
  lines.push(
    "on conflict (provider, external_park_id) do update set",
    "  park_id = excluded.park_id,",
    "  external_park_name = excluded.external_park_name,",
    "  updated_at = now();",
    "",
  );

  const out = join(process.cwd(), "supabase", "seeds", "live_wait_park_mappings.sql");
  writeFileSync(out, lines.join("\n"), "utf8");
  console.log(`Wrote ${out} (${rows.length} rows)`);
  const mapped = rows.filter((r) => r.parkId).length;
  console.log(`Mapped park_id: ${mapped}, null park_id: ${rows.length - mapped}`);
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
